name: Update Contributors

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'
  pull_request: # TODO: Remove PR trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Run contributor action
        uses: github/contributors@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Monthly contributor report
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./contributors.md
